/**
 * Development/demo seed data. NEVER run this against a production database —
 * it is not idempotent-safe for real user data (it upserts by fixed dev emails
 * and wipes/regenerates calling session history on every run).
 *
 * Historical sessions carry only aggregate counters (dials/conversations/
 * appointments), not a full per-event SessionEvent log — SessionEvent rows
 * are generated by real usage of the live active-session screen. Backfilling
 * tens of thousands of synthetic per-dial events for demo data isn't worth
 * the seed time; every historical number here is still real, additive, and
 * derived the same way live data would be.
 */
import "dotenv/config";
import { hash } from "bcryptjs";
import { PrismaClient } from "../lib/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { rebuildDailyAggregate } from "../lib/aggregation/daily";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const DEV_PASSWORD = "AscendDemo123!";

function randInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function pick<T>(items: T[]): T {
  return items[randInt(0, items.length - 1)];
}

async function main() {
  console.log("Seeding ASCEND development data...");
  const passwordHash = await hash(DEV_PASSWORD, 12);

  const team = await prisma.team.upsert({
    where: { name: "Core Sales Team" },
    update: {},
    create: { name: "Core Sales Team" },
  });

  const admin = await prisma.user.upsert({
    where: { email: "admin@ascend.dev" },
    update: {},
    create: { email: "admin@ascend.dev", name: "Alex Rivera", role: "ADMIN", passwordHash, teamId: team.id },
  });

  const managers = await Promise.all(
    [
      { email: "manager1@ascend.dev", name: "Jordan Blake" },
      { email: "manager2@ascend.dev", name: "Sam Whitfield" },
    ].map((m) =>
      prisma.user.upsert({
        where: { email: m.email },
        update: {},
        create: { ...m, role: "MANAGER", passwordHash, teamId: team.id },
      }),
    ),
  );

  // Each setter gets a rough skill multiplier applied when generating session
  // performance below — this is what makes the leaderboard/matrix meaningful.
  const setterDefs = [
    { email: "collin@ascend.dev", name: "Collin Dopp", skill: 1.25 },
    { email: "jake@ascend.dev", name: "Jake Sorensen", skill: 1.05 },
    { email: "tyler@ascend.dev", name: "Tyler Marsh", skill: 0.95 },
    { email: "brandon@ascend.dev", name: "Brandon Cole", skill: 0.85 },
    { email: "maya@ascend.dev", name: "Maya Chen", skill: 1.15 },
    { email: "priya@ascend.dev", name: "Priya Nair", skill: 1.0 },
  ];

  const setters = await Promise.all(
    setterDefs.map((s) =>
      prisma.user.upsert({
        where: { email: s.email },
        update: {},
        create: { email: s.email, name: s.name, role: "SETTER", passwordHash, teamId: team.id },
      }),
    ),
  );

  // Lead lists, each with a rough quality multiplier for generated performance.
  const leadListDefs = [
    {
      name: "Scout — Utah Homeowners",
      source: "Scout Data",
      location: "Utah",
      description: "Homeowner leads sourced via Scout Data, Utah territory.",
      leadCount: 5200,
      tags: ["scout", "homeowner", "utah"],
      quality: 1.2,
    },
    {
      name: "Old Appointments — Utah",
      source: "Internal Rehash",
      location: "Utah",
      description: "Previously set appointments being re-worked.",
      leadCount: 1400,
      tags: ["rehash", "utah"],
      quality: 1.3,
    },
    {
      name: "California Rehash",
      source: "Internal Rehash",
      location: "California",
      description: "Aged leads from prior California campaigns.",
      leadCount: 3100,
      tags: ["rehash", "california"],
      quality: 0.85,
    },
    {
      name: "High Equity — Utah",
      source: "Quickbase Import",
      location: "Utah",
      description: "High home-equity homeowner segment.",
      leadCount: 900,
      tags: ["high-equity", "utah"],
      quality: 1.1,
    },
    {
      name: "Scout — Texas Homeowners",
      source: "Scout Data",
      location: "Texas",
      description: "Homeowner leads sourced via Scout Data, Texas territory.",
      leadCount: 4300,
      tags: ["scout", "homeowner", "texas"],
      quality: 0.95,
    },
  ];

  const leadLists = await Promise.all(
    leadListDefs.map(async (l) => {
      const existing = await prisma.leadList.findFirst({ where: { name: l.name } });
      if (existing) return existing;
      return prisma.leadList.create({
        data: {
          name: l.name,
          source: l.source,
          location: l.location,
          description: l.description,
          leadCount: l.leadCount,
          tags: l.tags,
          createdById: admin.id,
        },
      });
    }),
  );

  console.log(`Seeded team, ${1} admin, ${managers.length} managers, ${setters.length} setters, ${leadLists.length} lead lists.`);

  // --- Historical calling sessions (last 21 days) ---
  // Clear only sessions/aggregates for these seeded setters so re-running the
  // script produces fresh, non-duplicated history instead of piling up.
  const setterIds = setters.map((s) => s.id);
  await prisma.dailyAggregate.deleteMany({ where: { setterId: { in: setterIds } } });
  await prisma.callingSession.deleteMany({ where: { setterId: { in: setterIds } } });

  const leadListQuality = new Map(leadListDefs.map((l, i) => [leadLists[i].id, l.quality]));
  const touchedKeys = new Set<string>();
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  let sessionCount = 0;

  for (const setter of setters) {
    const skill = setterDefs.find((s) => s.email === setter.email)!.skill;
    // Each setter mostly works 2-3 preferred lists, occasionally a fourth.
    const shuffled = [...leadLists].sort(() => Math.random() - 0.5);
    const preferredLists = shuffled.slice(0, randInt(2, 3));

    for (let dayOffset = 20; dayOffset >= 0; dayOffset--) {
      const day = new Date(today);
      day.setDate(day.getDate() - dayOffset);
      const dow = day.getDay();
      if (dow === 0 || dow === 6) {
        if (Math.random() > 0.25) continue; // mostly skip weekends
      }
      if (Math.random() > 0.85) continue; // occasional day off

      const sessionsToday = randInt(1, 2);
      for (let i = 0; i < sessionsToday; i++) {
        const leadList = pick(preferredLists);
        const quality = leadListQuality.get(leadList.id) ?? 1;

        const dials = randInt(35, 95);
        const baseConvRate = 0.12 * skill * quality;
        const conversations = Math.min(dials, Math.max(0, Math.round(dials * baseConvRate * (0.8 + Math.random() * 0.4))));
        const baseSetRate = 0.14 * skill * quality;
        const appointments = Math.min(
          conversations,
          Math.max(0, Math.round(conversations * baseSetRate * (0.7 + Math.random() * 0.6))),
        );

        const startHour = randInt(8, 15);
        const startedAt = new Date(day);
        startedAt.setHours(startHour, randInt(0, 59), 0, 0);
        const durationMinutes = randInt(45, 150);
        const endedAt = new Date(startedAt.getTime() + durationMinutes * 60_000);

        await prisma.callingSession.create({
          data: {
            setterId: setter.id,
            leadListId: leadList.id,
            startedAt,
            endedAt,
            status: "COMPLETED",
            dials,
            conversations,
            appointments,
          },
        });

        touchedKeys.add(JSON.stringify({ date: startedAt.toDateString(), setterId: setter.id, leadListId: leadList.id }));
        sessionCount += 1;
      }
    }
  }

  console.log(`Created ${sessionCount} historical calling sessions.`);

  for (const key of touchedKeys) {
    const { date, setterId, leadListId } = JSON.parse(key) as { date: string; setterId: string; leadListId: string };
    await rebuildDailyAggregate({ date: new Date(date), setterId, leadListId });
  }

  console.log(`Rebuilt ${touchedKeys.size} daily aggregate rows.`);
  console.log(`Dev password for all seeded users: ${DEV_PASSWORD}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
